# Generated by Django 3.0.5 on 2020-06-09 11:06

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeletedList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_no', models.CharField(max_length=50)),
                ('delete_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Lists',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_no', models.CharField(max_length=50)),
                ('isshared', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=500)),
                ('date', models.DateTimeField(default=None)),
                ('items', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=1000), blank=True, size=None)),
            ],
        ),
        migrations.CreateModel(
            name='Lists_Dates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_no', models.CharField(max_length=50)),
                ('updatedon', models.DateTimeField()),
                ('updatedby', models.EmailField(default=None, max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='MyLists',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('ishost', models.BooleanField(default=True)),
                ('list_no', models.CharField(max_length=50)),
            ],
        ),
    ]
