# Generated by Django 3.0.5 on 2020-06-09 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sharing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sharedto', models.EmailField(max_length=254)),
                ('list_no', models.CharField(max_length=50)),
                ('sharedon', models.DateTimeField()),
                ('host', models.EmailField(max_length=254)),
            ],
        ),
    ]
